# Generated by Django 2.2.7 on 2019-12-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_comics_comicsdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='comics',
            name='image_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
