# Generated by Django 2.2.7 on 2020-01-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_comics_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='title',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
