# Generated by Django 2.2.7 on 2020-01-29 11:56

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20200115_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='comics',
            name='title_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='comicsdetail',
            name='comic_imgs',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), default=[], max_length=251, size=12),
            preserve_default=False,
        ),
    ]
